name: Demo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

  strategy:
    matrix:
      node-version: [20.x]

  steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install and build
      run: npm install

    - name: Deploy
      uses: Jameslves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: build