name: Demo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensures 'deploy' runs after 'build' completes

    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages  # Checkout the gh-pages branch explicitly

      - name: Deploy to GitHub Pages (using latest stable action)
        uses: peaceiris/actions-gh-pages@v3  # Alternative with potential advantages
        with:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}  # Use dedicated token with repo permissions
          PUBLISH_DIR: ./build  # Provide the directory containing built files

      # Optional commit and push to gh-pages (consider using the alternative action's built-in functionality)
      - name: Push changes to gh-pages (optional)
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Deploy from workflow run #${{ github.run_id }}"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        if: always()  # Optionally commit and push changes to track deployments

