name: Demo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensures 'deploy' runs after 'build' completes

    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages  # Checkout the gh-pages branch explicitly

      - name: Deploy to GitHub Pages using peaceiris/actions-gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}  # Replace with personal access token with repo permissions
          PUBLISH_DIR: ./build  # Provide the directory containing built files
          USER_NAME: 'GitHub Actions Bot'  # Optional: Set custom commit user name
          USER_EMAIL: 'github-actions[bot]@users.noreply.github.com'  # Optional: Set custom commit email
          SKIP_PUSH: false  # Optionally keep this to allow the action to push changes (if allowed)

      # Alternative approach (optional): Push changes manually if SKIP_PUSH is true
      # - name: Push changes to gh-pages (optional)
      #   run: |
      #     git config --global user.name ${{ steps.deploy.outputs.GH_PAGES_USER_NAME }}
      #     git config --global user.email ${{ steps.deploy.outputs.GH_PAGES_USER_EMAIL }}
      #     git add .
      #     git commit -m "Deploy from workflow run #${{ github.run_id }}"
      #     git push origin gh-pages
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   if: always()  # Optionally commit and push changes to track deployments

